<?php

namespace AppBundle\Repository;

/**
 * localRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class localRepository extends \Doctrine\ORM\EntityRepository
{
}
