<?php

namespace AppBundle\Repository;

/**
 * materialeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class materialRepository extends \Doctrine\ORM\EntityRepository
{
}
