<?php

namespace AppBundle\Repository;

/**
 * OtroRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OtroRepository extends \Doctrine\ORM\EntityRepository
{
}
