<?php

namespace AppBundle\Repository;

/**
 * proveedorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class proveedorRepository extends \Doctrine\ORM\EntityRepository
{
}
